language: php

php:
  - 7.2

before_script:
  - composer self-update
  - composer global require franzl/studio

script:
  - composer install

after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo: false

