language: php

php:
  - 7.2

env:
  - COMPOSER_VERSION=1.6.2
  - COMPOSER_VERSION=1.6.3

before_script:
  - composer self-update $COMPOSER_VERSION
  - composer global require franzl/studio

script:
  - composer install

after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo: false

